# Generated by Django 4.2.5 on 2023-09-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='created_by',
        ),
    ]
