# Generated by Django 4.2.5 on 2023-09-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_parkingslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='unique_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
