# Generated by Django 4.2.5 on 2023-09-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_parkingslot_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='max_capacity',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
