# Generated by Django 4.2.5 on 2023-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_parking_max_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
