# Generated by Django 4.2.5 on 2023-09-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_parkingslot_unique_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parkingslot',
            constraint=models.UniqueConstraint(fields=('parking', 'unique_id'), name='unique_parking_slot'),
        ),
    ]
