# Generated by Django 4.2.5 on 2023-09-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_parkingslot_unique_parking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='unique_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
